### ISSUE TITLE
Flaky test : org.openflexo.foundation.fml.TestFlexoConceptInstanceType.testReloadViewPoint

### ISSUE THREAD

**Issue by sylvain-openflexo** [openflexo-team/openflexo-core#18]
Non deterministic failure on this test (and on some similar tests using testReloadViewPoint())

**Comment by sylvain-openflexo** [comment]
It might be caused because of non-atomic recursive directory copying
(Stack trace below)


java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.junit.Assert.assertNotNull(Assert.java:723)
	at org.openflexo.foundation.fml.TestFlexoConceptInstanceType.testReloadViewPoint(TestFlexoConceptInstanceType.java:370)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.GeneratedMethodAccessor445.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
	at sun.reflect.GeneratedMethodAccessor444.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)


Thread[Test worker,5,main]          WARNING 05/04/24 14:55:35,093  makeDelegateRC not implemented for [ClasspathResourceLocatorImpl]jar:file:/home/jenkins/jenkins-agent/workspace/openflexo-core-2.99/flexo-test-resources/build/libs/flexo-test-resources-2.99-SNAPSHOT.jar!/TestResourceCenter/PRJ/TestSingleInheritance.prj[org.openflexo.foundation.project.FlexoProjectResourceFactory.makeDelegateRC]
[PLEASE TRACK ME] : PAMELA edit received outside official recording. Create a default one !!!
Thread[AWT-EventQueue-1,6,main]     WARNING 05/04/24 14:55:35,287  Repository already registered: interface org.openflexo.foundation.fml.CompilationUnitRepository for CompilationUnitRepository$CompilationUnitRepositoryImpl_$$_jvst4ba_d:/tmp/Temp3840062487290588070TestResourceCenter[0][org.openflexo.foundation.resource.FileSystemBasedResourceCenter$FileSystemBasedResourceCenterImpl.registerRepository]
Thread[Test worker,5,main]          WARNING 05/04/24 14:55:35,337  makeDelegateRC not implemented for [ClasspathResourceLocatorImpl]jar:file:/home/jenkins/jenkins-agent/workspace/openflexo-core-2.99/flexo-test-resources/build/libs/flexo-test-resources-2.99-SNAPSHOT.jar!/TestResourceCenter/PRJ/TestSingleInheritance.prj[org.openflexo.foundation.project.FlexoProjectResourceFactory.makeDelegateRC]
[PLEASE TRACK ME] : PAMELA edit received outside official recording. Create a default one !!!
java.io.FileNotFoundException: /tmp/Temp6974058417407191404TestResourceCenter/TestFlexoConceptInstanceViewPoint.fml/TestFlexoConceptInstanceViewPoint.fml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.openflexo.foundation.resource.FileIODelegate$FileIODelegateImpl.getInputStream(FileIODelegate.java:239)
	at org.openflexo.foundation.resource.PamelaResourceImpl.getInputStream(PamelaResourceImpl.java:329)
	at org.openflexo.foundation.fml.rm.CompilationUnitResourceImpl.retrieveInfoFromFML(CompilationUnitResourceImpl.java:1276)
	at org.openflexo.foundation.fml.rm.CompilationUnitResourceImpl.findVirtualModelInfo(CompilationUnitResourceImpl.java:1193)
	at org.openflexo.foundation.fml.rm.CompilationUnitResourceImpl.getVirtualModelInfo(CompilationUnitResourceImpl.java:1144)
	at org.openflexo.foundation.fml.rm.CompilationUnitResourceFactory.initResourceForRetrieving(CompilationUnitResourceFactory.java:284)
	at org.openflexo.foundation.fml.rm.CompilationUnitResourceFactory.initResourceForRetrieving(CompilationUnitResourceFactory.java:54)
	at org.openflexo.foundation.resource.FlexoResourceFactory.retrieveResource(FlexoResourceFactory.java:196)
	at org.openflexo.foundation.technologyadapter.TechnologyAdapter.tryToLookupResource(TechnologyAdapter.java:354)
	at org.openflexo.foundation.technologyadapter.TechnologyAdapter.contentsAdded(TechnologyAdapter.java:399)
	at org.openflexo.foundation.resource.FileSystemBasedResourceCenter$FileSystemBasedResourceCenterImpl.fileAdded(FileSystemBasedResourceCenter.java:543)
	at org.openflexo.foundation.resource.FileSystemBasedResourceCenter$FileSystemBasedResourceCenterImpl$FileSystemBasedDirectoryWatcher.fileAdded(FileSystemBasedResourceCenter.java:421)
	at org.openflexo.toolbox.DirectoryWatcher$NodeDirectoryWatcher.watch(DirectoryWatcher.java:209)
	at org.openflexo.toolbox.DirectoryWatcher$NodeDirectoryWatcher.access$200(DirectoryWatcher.java:66)
	at org.openflexo.toolbox.DirectoryWatcher.performRun(DirectoryWatcher.java:393)
	at org.openflexo.foundation.resource.FileSystemBasedResourceCenter$FileSystemBasedResourceCenterImpl$FileSystemBasedDirectoryWatcher.performRun(FileSystemBasedResourceCenter.java:437)
	at org.openflexo.toolbox.DirectoryWatcher.run(DirectoryWatcher.java:377)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Thread[pool-7-thread-1,5,main]      WARNING 05/04/24 14:55:35,554  Unexpected exception in DirectoryWatcher java.lang.NullPointerException                             [org.openflexo.toolbox.DirectoryWatcher.run]      
java.lang.NullPointerException
	at org.openflexo.foundation.fml.rm.CompilationUnitResourceImpl.retrieveInfoFromFML(CompilationUnitResourceImpl.java:1288)
	at org.openflexo.foundation.fml.rm.CompilationUnitResourceImpl.findVirtualModelInfo(CompilationUnitResourceImpl.java:1193)
	at org.openflexo.foundation.fml.rm.CompilationUnitResourceImpl.getVirtualModelInfo(CompilationUnitResourceImpl.java:1144)
	at org.openflexo.foundation.fml.rm.CompilationUnitResourceFactory.initResourceForRetrieving(CompilationUnitResourceFactory.java:284)
	at org.openflexo.foundation.fml.rm.CompilationUnitResourceFactory.initResourceForRetrieving(CompilationUnitResourceFactory.java:54)
	at org.openflexo.foundation.resource.FlexoResourceFactory.retrieveResource(FlexoResourceFactory.java:196)
	at org.openflexo.foundation.technologyadapter.TechnologyAdapter.tryToLookupResource(TechnologyAdapter.java:354)
	at org.openflexo.foundation.technologyadapter.TechnologyAdapter.contentsAdded(TechnologyAdapter.java:399)
	at org.openflexo.foundation.resource.FileSystemBasedResourceCenter$FileSystemBasedResourceCenterImpl.fileAdded(FileSystemBasedResourceCenter.java:543)
	at org.openflexo.foundation.resource.FileSystemBasedResourceCenter$FileSystemBasedResourceCenterImpl$FileSystemBasedDirectoryWatcher.fileAdded(FileSystemBasedResourceCenter.java:421)
	at org.openflexo.toolbox.DirectoryWatcher$NodeDirectoryWatcher.watch(DirectoryWatcher.java:209)
	at org.openflexo.toolbox.DirectoryWatcher$NodeDirectoryWatcher.access$200(DirectoryWatcher.java:66)
	at org.openflexo.toolbox.DirectoryWatcher.performRun(DirectoryWatcher.java:393)
	at org.openflexo.foundation.resource.FileSystemBasedResourceCenter$FileSystemBasedResourceCenterImpl$FileSystemBasedDirectoryWatcher.performRun(FileSystemBasedResourceCenter.java:437)
	at org.openflexo.toolbox.DirectoryWatcher.run(DirectoryWatcher.java:377)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Thread[Test worker,5,main]          WARNING 05/04/24 14:55:35,564  STOP Method for service should be overriden in each service [org.openflexo.foundation.localization.DefaultLocalizationService][org.openflexo.foundation.FlexoServiceImpl.stop]  
Thread[Test worker,5,main]          WARNING 05/04/24 14:55:35,564  STOP Method for service should be overriden in each service [org.openflexo.foundation.resource.ResourceManager][org.openflexo.foundation.FlexoServiceImpl.stop]  
Thread[Test worker,5,main]          WARNING 05/04/24 14:55:35,564  STOP Method for service should be overriden in each service [org.openflexo.foundation.test.OpenflexoTestCase.TestProjectLoader][org.openflexo.foundation.FlexoServiceImpl.stop]  
Thread[Test worker,5,main]          WARNING 05/04/24 14:55:35,564  STOP Method for service should be overriden in each service [org.openflexo.foundation.nature.DefaultProjectNatureService_$$_jvst4ba_0][org.openflexo.foundation.FlexoServiceImpl.stop]  
Thread[Test worker,5,main]          WARNING 05/04/24 14:55:35,564  STOP Method for service should be overriden in each service [org.openflexo.foundation.technologyadapter.DefaultTechnologyAdapterService_$$_jvst4ba_8][org.openflexo.foundation.FlexoServiceImpl.stop]  
Thread[Test worker,5,main]          WARNING 05/04/24 14:55:35,565  STOP Method for service should be overriden in each service [org.openflexo.foundation.fml.VirtualModelLibrary][org.openflexo.foundation.fml.VirtualModelLibrary.stop]
Thread[Test worker,5,main]          WARNING 05/04/24 14:55:35,565  STOP Method for service should be overriden in each service [org.openflexo.foundation.nature.DefaultScreenshotService_$$_jvst4ba_10][org.openflexo.foundation.FlexoServiceImpl.stop]
