### ISSUE TITLE
A NullPointerException when creating multiple actions in the same behaviour

### ISSUE THREAD

**Issue by OverFlow33** [openflexo-team/openflexo-core#6]
I'm currently using 2.0.1-ihab and when i try to create multiple behaviour actions (usually when creating more than 2 actions per behaviour) i got a NullPointerException.

`Exception java.lang.NullPointerException:
	at org.openflexo.foundation.fml.controlgraph.Sequence$SequenceImpl.sequentiallyAppend(Sequence.java:143)
	at org.openflexo.foundation.fml.action.CreateEditionAction.doAction(CreateEditionAction.java:271)
	at org.openflexo.foundation.action.FlexoAction.doActionInContext(FlexoAction.java:271)
	at org.openflexo.foundation.DefaultFlexoEditor.performAction(DefaultFlexoEditor.java:156)
	at org.openflexo.foundation.action.FlexoAction.doAction(FlexoAction.java:231)
	at org.openflexo.http.server.core.controllers.BehavioursController.addAssignation(BehavioursController.java:347)`

**Comment by sylvain-openflexo** [comment]
This bug is not related to openflexo-http and should be moved to openflexo-core

**Comment by sylvain-openflexo** [comment]
This bug should be implemented as a unit test in openflexo-core/flexo-foundation-test
